import classNames from "classnames";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Electrolize } from "next/font/google";
import * as shader from "./_shaders/bg_shader";
import { Shader } from "./_components/shader";

const inter = Inter({ subsets: ["latin"] });
export const ElectrolizeFont = Electrolize({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	console.log(shader.default);
	return (
		<html lang="en">
			<body
				className={classNames(
					inter.className,
					"text-white bg-transparent text-lg"
				)}
			>
				<Shader />
				{children}
			</body>
		</html>
	);
}
