import classNames from "classnames";
import type { Metadata } from "next";
import { Electrolize, Gloria_Hallelujah, Inter } from "next/font/google";
import { Shader } from "./_components/shader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const ElectrolizeFont = Electrolize({
	weight: "400",
	subsets: ["latin"],
});
export const WeirdFont = Gloria_Hallelujah({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={classNames(
					inter.className,
					"text-white bg-foundation text-lg"
				)}
			>
				<Shader />
				{children}
			</body>
		</html>
	);
}
